### ISSUE TITLE
A4.2. Acuerdo de cliente - Duración

### ISSUE THREAD

**Issue by Miguel-Angel-Roldan-Garcia** [gii-is-psg2/psg2-2223-g6-61#65]
- Duración: Al menos durante la totalidad del curso académico.

**Comment by isma13** [comment]
Añadido también el apartado de Licencia de uso para Petclinic

**Comment by Samalbalat** [comment]
Revisión realizada
- Correcciones ortográficas múltiples al propio documento
- Finalización del apartado de Definiciones
- Reestructuración de maquetación para ajuste de la visualización del documento
