### ISSUE TITLE
A4.2. Acuerdo de cliente - Servicios asociados y descripción

### ISSUE THREAD

**Issue by Miguel-Angel-Roldan-Garcia** [gii-is-psg2/psg2-2223-g6-61#66]
- Servicios asociados y descripción: Petclinic4CO. Permite a sus usuarios (Dueños de clínicas) pedir la resolución de incidencias, peticiones de usuarios y estimaciones de Peticiones de Cambios (PDC, "Request For Changes, RFC").

**Comment by olemornav** [comment]
Se ha creado una primera versión del apartado en la que se propone un formato por tablas

**Comment by Samalbalat** [comment]
Confirmado, está en orden y en el documento, todo bien
