### ISSUE TITLE
A4.2. Acuerdo de cliente - Tarifas

### ISSUE THREAD

**Issue by Miguel-Angel-Roldan-Garcia** [gii-is-psg2/psg2-2223-g6-61#67]
Tarifas: Tienen que existir al menos tres planes (Basico, Avanzado y Pro), cuyas condiciones pueden ser establecidas por cada grupo a su conveniencia, siempre que las siguientes restricciones se cumplan:
- El plan Basico no ofrece SLA (service-level agreement).
- El plan Avanzado es el primero que permite a los dueños de las clínicas controlar multiples clínicas de mascotas.
- El plan Pro es el único que ofrece soporte para peticiones de usuario y RFCs.
- El máximo número de veterinarios, visitas mensuales y tipos de mascota permitidos deben diferir para cada plan.
- La disponibilidad del servicio debe ser diferente para cada plan. Esta información debe estar representada usando una matriz, como es obligatorio hoy día.

**Comment by olemornav** [comment]
Problemas que he visto que podrían mejorar:
-Se me hace raro que pueda tener 40 tipos de mascotas diferentes, pondría números más bajos.
-Se podría colorear la tabla con los tonos de la plantilla para dejar un documento más vistoso.
-En lugar de usar "SÍ" o "NO" creo que quedaría mejor usar ✔️/❌.

Son problemas sencillos de arreglar y que no tienen mucha importancia pero creo que mejorarían el resultado final.

**Comment by Miguel-Angel-Roldan-Garcia** [comment]
Quedan arregladas todas esas anotaciones.

**Comment by olemornav** [comment]
Tras la revisión no se han detectado más problemas, todo en orden
