### ISSUE TITLE
A4.2. Acuerdo de cliente - Representación HTML

### ISSUE THREAD

**Issue by Miguel-Angel-Roldan-Garcia** [gii-is-psg2/psg2-2223-g6-61#70]
Construir el nuevo menu de Pet Clinic conteniendo el acuerdo de cliente y el acuerdo de nivel de servicio en HTML

**Comment by isma13** [comment]
Incluida la nueva página de CA junto con SLA que es accesible desde una nueva opción de menú "Acuerdo de cliente".

**Comment by olemornav** [comment]
El contenido se ajusta a lo solicitado
