### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Moffinguer** [gii-is-psg2/psg2-2223-g6-61#73]

**Comment by olemornav** [comment]
Al pulsar en el enlace hacia changelog salta error Exception in thread "http-nio-8080-ClientPoller" java.lang.OutOfMemoryError: Java heap space

**Comment by olemornav** [comment]
El bucle infinito ha sido corregido y se muestra el contenido requerido. Como anotación se podría mejorar la vista en un futuro.
