### ISSUE TITLE
SupportPage

### ISSUE THREAD

**Issue by Moffinguer** [gii-is-psg2/psg2-2223-g6-61#74]

**Comment by olemornav** [comment]
-La página de contacto posee un contenido correcto pero se podría mejorar visualmente con tablas o dando formato a los textos.

-La página de welcome posee errores de escritura.

**Comment by olemornav** [comment]
Tras una segunda revisión la página welcome continuaba con errores en símbolos que han sido corregidos personalmente. Todo correcto
